// components
import ReactMarkdown from 'react-markdown';
import Head from 'next/head';
// -- custom
import HeroImage from '../components/HeroImage/HeroImage';
import ImageReel from '../components/ImageReel/ImageReel';
import NoData from '../components/NoData/NoData';

// utils
import { queryStrapi } from '../utils/query-strapi';

// styles
import styles from '../styles/pages/About.module.scss';

// constants
import { partnerLogos } from '../constants';
import { GET_ABOUT_CONTENT } from '../graphql/queries';

export default function About({ content }) {
  return (
    <>
      <Head>
        <title>About | FreeRoam</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeroImage
        title="About Us"
        src="/team.jpg"
        alt="team of people in deep discussion"
      />

      <main className={styles.about}>
        {content ? (
          <article>
            <ReactMarkdown>{content}</ReactMarkdown>
          </article>
        ) : (
          <NoData />
        )}

        {/* Our Partners - autoplay infinity scroll */}
        <section>
          <ImageReel title="Our Partners" images={partnerLogos} />
        </section>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const { about } = await queryStrapi(GET_ABOUT_CONTENT);

  return {
    props: {
      content: about.data.attributes.content,
    },
    revalidate: 10,
  };
}
