// components
import ReactMarkdown from 'react-markdown';
import Head from 'next/head';
// -- custom
import HeroImage from '../components/HeroImage/HeroImage';

// styles
import styles from '../styles/pages/About.module.scss';

// constants
import { STRAPI_URL } from '../constants';

export default function About({ content }) {
  return (
    <>
      <Head>
        <title>About | FreeRoam</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeroImage title="About Us" imageUrl="/team.jpg" />

      <main className={styles.about}>
        <ReactMarkdown>{content}</ReactMarkdown>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const fetchOptions = {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({
      query: `{
        about {
          data {
            id
            attributes {
              content
            }
          }
        }
      }`,
    }),
  };
  const response = await fetch(`${STRAPI_URL}/graphql`, fetchOptions);
  const result = await response.json();
  const { about } = result.data;
  console.log({ about });

  return {
    props: {
      content: about.data.attributes.content,
    },
  };
}
