// components
import ReactMarkdown from 'react-markdown';
import Head from 'next/head';
// -- custom
import HeroImage from '../components/HeroImage/HeroImage';
import ImageReel from '../components/ImageReel/ImageReel';

// styles
import styles from '../styles/pages/About.module.scss';

// constants
import { STRAPI_URL, partnerLogos } from '../constants';
import { GET_ABOUT_CONTENT } from '../graphql/queries';

export default function About({ content }) {
  return (
    <>
      <Head>
        <title>About | FreeRoam</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeroImage title="About Us" imageUrl="/team.jpg" />

      <main className={styles.about}>
        <article>
          <ReactMarkdown>{content}</ReactMarkdown>
        </article>

        {/* Our Partners - autoplay infinity scroll */}
        <section>
          <ImageReel title="Our Partners" images={partnerLogos} />
        </section>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const fetchOptions = {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({
      query: GET_ABOUT_CONTENT,
    }),
  };
  const response = await fetch(`${STRAPI_URL}/graphql`, fetchOptions);
  const result = await response.json();
  const { about } = result.data;

  return {
    props: {
      content: about.data.attributes.content,
    },
  };
}
