// components
import Head from 'next/head';
// -- custom
import ImageSlider from '../components/ImageSlider/ImageSlider';

// styles
import styles from '../styles/pages/Home.module.scss';

// constants
import { homeSlides } from '../constants';

export default function Home() {
  return (
    <>
      <Head>
        <title>Home | FreeRoam</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.home}>
        <section>
          <ImageSlider
            slides={homeSlides}
            width={1000}
            height={600}
            withTextOverlay
          />
        </section>
      </main>
    </>
  );
}
